name       : CI Pipeline - DEV
on:
  push:
    branches:
      - dev

env:
  GIT__BRANCH         : 'dev'
  PACKAGE_NAME        : 'cbr_web_components'

jobs:

  increment-tag:
    if: False
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag (for DEV)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type : 'minor'

  run-qunit-tests:
    name: Run QUnit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run QUnit Tests
        uses: ./.github/actions/run-qunit-tests
        with:
          node-version: '22.4.1'

