name       : CI Pipeline - DEV
on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  GIT__BRANCH         : 'dev'
  PACKAGE_NAME        : 'cbr_web_components'

jobs:

  run-qunit-tests:
    if: False
    name: Run QUnit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true                              # Ensures submodules are checked out
          token: ${{ secrets.GIT_HUB__ACCESS_TOKEN }}

      - name: Run QUnit Tests
        uses: ./.github/actions/run-qunit-tests
        with:
          node-version: '22.4.1'

  increment-tag:
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag (for DEV)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: 'minor'
    needs:
      - run-qunit-tests

#  trigger-deploy-community-dev:
#    name: "Deploy Community (DEV)"
#    runs-on: ubuntu-latest
#    steps:
#      - name: Trigger target repository workflow
#        run: |
#          curl -X POST \
#          -H "Accept: application/vnd.github.v3+json" \
#          -H "Authorization: token ${{ secrets.GIT_HUB__ACCESS_TOKEN }}" \
#          https://api.github.com/repos/the-cyber-boardroom/cbr-community/dispatches \
#          -d '{"event_type":"deploy-community-dev"}'
#    needs:
#      - increment-tag

  publish-to-pypi:
    permissions:
      id-token: write
    name: "Publish to PYPI"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__publish@dev
    needs:
      - increment-tag

  publish-static-files-to-s3:
    name: Publish Static Files to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/aws__publish__s3_via_cloudfront@dev
        env:
          AWS_ACCOUNT_ID       : ${{ secrets.AWS_ACCOUNT_ID__654654216424        }}
          AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID__654654216424     }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY__654654216424 }}
          AWS_DEFAULT_REGION   : ${{ secrets.AWS_DEFAULT_REGION__654654216424    }}
          CLOUDFRONT_DIST_ID   : ${{ secrets.CLOUDFRONT_DIST_ID                  }}
          S3_PUBLISH_BUCKET    : cyber-boardroom-654654216424-public
          S3_PUBLISH_FOLDER    : cbr-web-components
          PACKAGE_NAME         : cbr_web_components
#    needs:
#      - increment-tag

