name       : CI Pipeline - MAIN
on:
  push:
    branches:
      - main

env:
  GIT__BRANCH         : 'main'
  PACKAGE_NAME        : 'cbr_web_components'

jobs:

  run-qunit-tests:
    name: Run QUnit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run QUnit Tests
        uses: ./.github/actions/run-qunit-tests
        with:
          node-version: '22.4.1'

  increment-tag:
    name: Increment Tag - MAIN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag (for MAIN)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type : 'major'
    needs:
      - run-qunit-tests

  publish-to-pypi:
    permissions:
      id-token: write
    name: "Publish to PYPI"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__publish@dev
    needs:
      - increment-tag
